# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-19 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('recommender_id', models.IntegerField()),
                ('login_name', models.CharField(max_length=128)),
                ('login_passwd', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pause_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('real_name', models.CharField(max_length=128)),
                ('idcard_no', models.CharField(max_length=128)),
                ('birthdate', models.DateField()),
                ('gender', models.BooleanField()),
                ('occupation', models.CharField(max_length=128)),
                ('telephone', models.IntegerField()),
                ('email', models.CharField(max_length=64)),
                ('mailaddress', models.CharField(max_length=256)),
                ('zipcode', models.IntegerField()),
                ('qq', models.IntegerField()),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
