# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login_ip',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='qq',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='recommender_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
