# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_auto_20191020_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mailaddress',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
