# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_auto_20191020_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pause_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
