# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0008_auto_20191021_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.NullBooleanField(default=True),
        ),
    ]
